version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ecuser
      POSTGRES_PASSWORD: ecpass
      POSTGRES_DB: ecdemo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
